export const nationalities = [
        { id: 0, label: 'Afghanistan' },
        { id: 1, label: 'Autre' },
        { id: 2, label: 'Afrique du Sud' },
        { id: 3, label: 'Albanie' },
        { id: 4, label: 'Algerie' },
        { id: 5, label: 'Allemagne' },
        { id: 6, label: 'Andorre' },
        { id: 7, label: 'Angleterre' },
        { id: 8, label: 'Angola' },
        { id: 9, label: 'Anguilla' },
        { id: 10, label: 'Antigua et Barbuda' },
        { id: 11, label: 'Antilles neerlandaises' },
        { id: 12, label: 'Arabie Saoudite' },
        { id: 13, label: 'Argentine' },
        { id: 14, label: 'Armenie' },
        { id: 15, label: 'Aruba' },
        { id: 16, label: 'Australie' },
        { id: 17, label: 'Autriche' },
        { id: 18, label: 'Azerbaidjan' },
        { id: 19, label: 'Bahamas' },
        { id: 20, label: 'Bahrein' },
        { id: 21, label: 'Bangladesh' },
        { id: 22, label: 'Barbade' },
        { id: 23, label: 'Belgique' },
        { id: 24, label: 'Belize' },
        { id: 25, label: 'Bermudes' },
        { id: 26, label: 'Bhoutan' },
        { id: 27, label: 'Bolivie' },
        { id: 28, label: 'Bosnie-Herzegovine' },
        { id: 29, label: 'Botswana' },
        { id: 30, label: 'Brunei' },
        { id: 31, label: 'Bresil' },
        { id: 32, label: 'Bulgarie' },
        { id: 33, label: 'Burkina Faso' },
        { id: 34, label: 'Burundi' },
        { id: 35, label: 'Belarus' },
        { id: 36, label: 'Benin' },
        { id: 37, label: 'Cambodge' },
        { id: 38, label: 'Cameroun' },
        { id: 39, label: 'Canada' },
        { id: 40, label: 'Cap Vert' },
        { id: 41, label: 'Chili' },
        { id: 42, label: 'Chine RP' },
        { id: 43, label: 'Chinese Taipei' },
        { id: 44, label: 'Chypre' },
        { id: 45, label: 'Colombie' },
        { id: 46, label: 'Congo' },
        { id: 47, label: 'Congo RD' },
        { id: 48, label: 'Costa Rica' },
        { id: 49, label: 'Croatie' },
        { id: 50, label: 'Cuba' },
        { id: 51, label: 'COTE DIVOIRE' },
        { id: 52, label: 'Danemark' },
        { id: 53, label: 'Djibouti' },
        { id: 54, label: 'Dominique' },
        { id: 55, label: 'Ecosse' },
        { id: 56, label: 'Egypte' },
        { id: 57, label: 'Emirats Arabes Unis' },
        { id: 58, label: 'Equateur' },
        { id: 59, label: 'Erythree' },
        { id: 60, label: 'Espagne' },
        { id: 61, label: 'Estonie' },
        { id: 62, label: 'Etats-Unis d\'Amerique' },
        { id: 63, label: 'Ethiopie' },
        { id: 64, label: 'Fidji' },
        { id: 65, label: 'Finlande' },
        { id: 66, label: 'France' },
        { id: 67, label: 'Gabon' },
        { id: 68, label: 'Gambie' },
        { id: 69, label: 'Ghana' },
        { id: 70, label: 'Grenade' },
        { id: 71, label: 'Grece' },
        { id: 72, label: 'Guam' },
        { id: 73, label: 'Guatemala' },
        { id: 74, label: 'Guinee' },
        { id: 75, label: 'Guinee Equatoriale' },
        { id: 76, label: 'Guinee-Bissau' },
        { id: 77, label: 'Guyana' },
        { id: 78, label: 'Georgie' },
        { id: 79, label: 'Haiti' },
        { id: 80, label: 'Honduras' },
        { id: 81, label: 'Hong-Kong' },
        { id: 82, label: 'Hongrie' },
        { id: 83, label: 'Iles Caimans' },
        { id: 84, label: 'Iles Cook' },
        { id: 85, label: 'Iles Feroe' },
        { id: 86, label: 'Iles Maldives' },
        { id: 87, label: 'Iles Salomon' },
        { id: 88, label: 'Iles Vierges americaines' },
        { id: 89, label: 'Iles Vierges britanniques' },
        { id: 90, label: 'Inde' },
        { id: 91, label: 'Indonesie' },
        { id: 92, label: 'Irak' },
        { id: 93, label: 'Iran' },
        { id: 94, label: 'Irlande du Nord' },
        { id: 95, label: 'Islande' },
        { id: 96, label: 'Israel' },
        { id: 97, label: 'Italie' },
        { id: 98, label: 'Jamaique' },
        { id: 99, label: 'Japon' },
        { id: 100, label: 'Jordanie' },
        { id: 101, label: 'Kazakhstan' },
        { id: 102, label: 'Kenya' },
        { id: 103, label: 'Kirghizistan' },
        { id: 104, label: 'Koweit' },
        { id: 105, label: 'Laos' },
        { id: 106, label: 'Lesotho' },
        { id: 107, label: 'Lettonie' },
        { id: 108, label: 'Liban' },
        { id: 109, label: 'Libye' },
        { id: 110, label: 'Liberia' },
        { id: 111, label: 'Liechtenstein' },
        { id: 112, label: 'Lituanie' },
        { id: 113, label: 'Luxembourg' },
        { id: 114, label: 'Macao' },
        { id: 115, label: 'Macedoine FYR' },
        { id: 116, label: 'Madagascar' },
        { id: 117, label: 'Malaisie' },
        { id: 118, label: 'Malawi' },
        { id: 119, label: 'Mali' },
        { id: 120, label: 'Malte' },
        { id: 121, label: 'Maroc' },
        { id: 122, label: 'Maurice' },
        { id: 123, label: 'Mauritanie' },
        { id: 124, label: 'Mexique' },
        { id: 125, label: 'Moldavie' },
        { id: 126, label: 'Mongolie' },
        { id: 127, label: 'Montserrat' },
        { id: 128, label: 'Mozambique' },
        { id: 129, label: 'Myanmar' },
        { id: 130, label: 'Namibie' },
        { id: 131, label: 'Nicaragua' },
        { id: 132, label: 'Niger' },
        { id: 133, label: 'NIGERIA' },
        { id: 134, label: 'Norvege' },
        { id: 135, label: 'Nouvelle-Zelande' },
        { id: 136, label: 'Nepal' },
        { id: 137, label: 'Oman' },
        { id: 138, label: 'Ouganda' },
        { id: 139, label: 'Ouzbekistan' },
        { id: 140, label: 'Pakistan' },
        { id: 141, label: 'Palestine' },
        { id: 142, label: 'Panama' },
        { id: 143, label: 'Papouasie-Nouvelle-Guinee' },
        { id: 144, label: 'Paraguay' },
        { id: 145, label: 'Pays de Galles' },
        { id: 146, label: 'Pays-Bas' },
        { id: 147, label: 'Philippines' },
        { id: 148, label: 'Pologne' },
        { id: 149, label: 'Porto Rico' },
        { id: 150, label: 'Portugal' },
        { id: 151, label: 'Perou' },
        { id: 152, label: 'Qatar' },
        { id: 153, label: 'RDP Coree' },
        { id: 154, label: 'Roumanie' },
        { id: 155, label: 'Russie' },
        { id: 156, label: 'Rwanda' },
        { id: 157, label: 'Republique Centrafricaine' },
        { id: 158, label: 'Republique Dominicaine' },
        { id: 159, label: 'Republique d\'Irlande' },
        { id: 160, label: 'Republique de Coree' },
        { id: 161, label: 'Republique tcheque' },
        { id: 162, label: 'Saint Christophe et Nevis' },
        { id: 163, label: 'Saint Marin' },
        { id: 164, label: 'Salvador' },
        { id: 165, label: 'Samoa' },
        { id: 166, label: 'Samoa americaines' },
        { id: 167, label: 'Sao Tome e Principe' },
        { id: 168, label: 'Serbie et Montenegro' },
        { id: 169, label: 'Seychelles' },
        { id: 170, label: 'Sierra Leone' },
        { id: 171, label: 'Singapour' },
        { id: 172, label: 'Slovaquie' },
        { id: 173, label: 'Slovenie' },
        { id: 174, label: 'Somalie' },
        { id: 175, label: 'Soudan' },
        { id: 176, label: 'Sri Lanka' },
        { id: 177, label: 'St-Vincent et Grenadines' },
        { id: 178, label: 'Ste-Lucie' },
        { id: 179, label: 'Suisse' },
        { id: 180, label: 'Surinam' },
        { id: 181, label: 'Suede' },
        { id: 182, label: 'Swaziland' },
        { id: 183, label: 'Syrie' },
        { id: 184, label: 'Senegal' },
        { id: 185, label: 'Tadjikistan' },
        { id: 186, label: 'Tahiti' },
        { id: 187, label: 'Tanzanie' },
        { id: 188, label: 'Tchad' },
        { id: 189, label: 'Thailande' },
        { id: 190, label: 'Togo' },
        { id: 191, label: 'Tonga' },
        { id: 192, label: 'Trinite et Tobago' },
        { id: 193, label: 'TUNISIE' },
        { id: 194, label: 'Turkmenistan' },
        { id: 195, label: 'Turks et Caicos' },
        { id: 196, label: 'Turquie' },
        { id: 197, label: 'Ukraine' },
        { id: 198, label: 'Uruguay' },
        { id: 199, label: 'Vanuatu' },
        { id: 200, label: 'Venezuela' },
        { id: 201, label: 'Viet-Nam' },
        { id: 202, label: 'Yemen' },
        { id: 203, label: 'Zambie' },
        { id: 204, label: 'Zimbabwe' },
        { id: 205, label: 'Kosovo' }
    ];